// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ZPOF0JlVv2jjpxGY36MrLRmTOK4KiHY',
    appId: '1:196805083197:web:777d377e3107a742e2ea54',
    messagingSenderId: '196805083197',
    projectId: 'wechat-e9ad3',
    authDomain: 'wechat-e9ad3.firebaseapp.com',
    storageBucket: 'wechat-e9ad3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBJ4_ih6P5vXnGzZAnE2lkVluIEqgMJk',
    appId: '1:196805083197:android:a4d84ecbca374fa0e2ea54',
    messagingSenderId: '196805083197',
    projectId: 'wechat-e9ad3',
    storageBucket: 'wechat-e9ad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6NvvE0ZjV9hn_SGKBsdKodaUBc5E5L8',
    appId: '1:196805083197:ios:1c2f8881d33b6426e2ea54',
    messagingSenderId: '196805083197',
    projectId: 'wechat-e9ad3',
    storageBucket: 'wechat-e9ad3.appspot.com',
    androidClientId: '196805083197-20u1db3dr8o98mhrtks9b4co0e845fs5.apps.googleusercontent.com',
    iosClientId: '196805083197-roos3hhe02usfp263f9u57cql4it9k52.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
